name: Build and Deploy fastapi
on: [push, pull_request]
jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: rajesh1234@
      DATABASE_USERNAME: postgres
      DATABASE_NAME: fastapi
      SECRET_KEY: H09d25e094faa6ca255djghdgjdg5636565656b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHIM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: pull the github repo
        uses: actions/checkout@v2
      - name: setting up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      - name: upgarde pip
        run:  python -m pip install --upgrade pip
      - name: install all dependencies
        run:  pip install -r requirements.txt
      - name: run pytest
        run:  |
          pip install pytest
          pytest


        
      
