name: Build and Deploy fastapi
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull the github repo
        uses: actions/checkout@v2
      - name: say hi
        run:  echo "helloooooooooooooooooooooooo" 
      
